services:
  mysql:
    image: mysql:8.0
    container_name: mysql-app
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - employee-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    image: employee-management_backend:v2
    container_name: back-app
    restart: unless-stopped

    ports:
      - "8081:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - employee-network
  frontend:
   build:
    context: ./frontend
   image: employee-management_frontend:v2
   container_name: front-app
   restart: unless-stopped

   ports:
    - "5173:5173"

   depends_on:
    - backend

   networks:
    - employee-network

volumes:
  mysql-data:

networks:
  employee-network:
    name: employee-network
    driver: bridge
