apiVersion: v1
kind: Service

metadata:
  name: employee-backend-service
  namespace: employee-management

spec:
  type: ClusterIP

  selector:
    app: employee-backend

  ports:
    - port: 8080
      targetPort: 8080